### ISSUE TITLE
Where can I find "--ckpt"?

### ISSUE THREAD

**Issue by yizhangliu** [adobe-research/custom-diffusion#11]
Such as, python src/compress.py --delta_ckpt <finetuned-delta-path> --ckpt <pretrained-model-path>
Here:   pretrained-model-path="CompVis/stable-diffusion-v1-4"?
But:  FileNotFoundError: [Errno 2] No such file or directory: 'CompVis/stable-diffusion-v1-4'

**Comment by nupurkmr9** [comment]
Hi, 
The compression code currently only supports [CompVis/stable-diffusion](https://github.com/CompVis/stable-diffusion) checkpoints. Thus the --ckpt should be the model downloaded from [here](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt). 
I will soon add the support for compression in the diffusers based models as well. 

Thanks.

**Comment by yizhangliu** [comment]
@nupurkmr9  Thanks.

**Comment by yizhangliu** [comment]
!python  src/compress.py --delta_ckpt='logs/person/delta.bin'  --ckpt='sd-v1-4.ckpt'

    Traceback (most recent call last):
      File "src/compress.py", line 63, in <module>
        compress(args.delta_ckpt, args.ckpt)
      File "src/compress.py", line 17, in compress
        if 'embed' in st['state_dict']:
    KeyError: 'state_dict'

**Comment by nupurkmr9** [comment]
Hi, I have updated the compression code to support diffusers library based models as well. Please run the below commands for compression and sampling from the compressed model. Sorry for any confusion. 
```
python src/compress.py --delta_ckpt='logs/person/delta.bin'  --ckpt "CompVis/stable-diffusion-v1-4" --diffuser

python src/sample_diffuser.py  --delta_ckpt='logs/person/compressed_delta.bin'  --ckpt "CompVis/stable-diffusion-v1-4"  --prompt "text-prompt"  --compress 
```
Thanks.

**Comment by yizhangliu** [comment]
!python src/compress.py --delta_ckpt='logs/person/delta.bin'  --ckpt "CompVis/stable-diffusion-v1-4" --diffuser

    Fetching 16 files: 100% 16/16 [00:00<00:00, 4506.37it/s]
    getting compression
    Traceback (most recent call last):
      File "src/compress.py", line 66, in <module>
        compress(args.delta_ckpt, args.ckpt, args.diffuser)
      File "src/compress.py", line 37, in compress
        u, s, vt = torch.linalg.svd(deltaW.clone())
    RuntimeError: linalg.svd: The input tensor A must have at least 2 dimensions.

**Comment by nupurkmr9** [comment]
Hi, is the diffuser model trained with default configurations or with `--freeze_model crossattn`?

**Comment by yizhangliu** [comment]
@nupurkmr9 
the dimensionality of A：  torch.Size([320]）
layer_name:   down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_out.0.bias

**Comment by yizhangliu** [comment]
> what to do if you used --freeze_model crossattn beacause i used it and i get this error
> 
> ```
> Traceback (most recent call last):
>   File "src/compress.py", line 63, in <module>
>     compress(args.delta_ckpt, args.ckpt)
>   File "src/compress.py", line 17, in compress
>     if 'embed' in st['state_dict']:
> KeyError: 'state_dict'
> ```

@TingTingin 
You should use:
python src/compress.py --delta_ckpt='logs/person/delta.bin'  --ckpt "CompVis/stable-diffusion-v1-4" --diffuser

**Comment by nupurkmr9** [comment]
Hi, 

The compression code now also supports `--freeze_model=crossattn_kv`. 

But compression of key and value projections matrices for models fine-tuned with `freeze_model=crossattn` leads to significant differences b/w the base and compressed model.

**Comment by yizhangliu** [comment]
@nupurkmr9  Thanks.
