### ISSUE TITLE
composenW for diffuser codes

### ISSUE THREAD

**Issue by guyuchao** [adobe-research/custom-diffusion#18]
Hello, will you plan to release the composenW code for diffuser codes.

**Comment by nupurkmr9** [comment]
Hi, 
Yes, will release it by next week. Thanks for creating the issue regarding it.

**Comment by guyuchao** [comment]
Is there any update?

**Comment by nupurkmr9** [comment]
Hi, 
Sorry for the delay. I have updated the code now to allow delta checkpoint merging for diffuser models using [composenW_diffuser.py](https://github.com/adobe-research/custom-diffusion/blob/main/src/composenW_diffuser.py) as explained in this [section](https://github.com/adobe-research/custom-diffusion#training-using-diffusers-library). 
Let me know if you face any issues. Thanks!

**Comment by guyuchao** [comment]
Thanks.
