### ISSUE TITLE
Evaluation Prompts

### ISSUE THREAD

**Issue by atjeong** [adobe-research/custom-diffusion#29]
Firstly, thank you for your great work. :)

I saw the prompts folder that you uploaded.
For single concept evaluation, the prompts includes the customized token (<new1>).
Did you use the same prompts for evaluating text alignment?

**Comment by nupurkmr9** [comment]
Hi,
We only use the modifier token, e.g., \<new1\> or \<new2\>, during the generation with customized models.
For evaluation of text-alignment, these tokens are removed from the sentence before calculating CLIP text features. 
Thanks for clarifying it.

**Comment by atjeong** [comment]
Thank you for your kind reply. :)
