### ISSUE TITLE
How to use the finetune_face.yaml?

### ISSUE THREAD

**Issue by dawei03896** [adobe-research/custom-diffusion#39]
I want to fineturn face image use finetune_face.yaml , but I don't find pretrained model, how to use the finetune_face.yaml?

**Comment by nupurkmr9** [comment]
Hi, 
you can download the pretrained model to be used with CompVis based code [here](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt).
