### ISSUE TITLE
Wich license is right?

### ISSUE THREAD

**Issue by jaspior** [adobe-research/custom-diffusion#4]
So, which license apply to custom diffusion? Here at the repo, we have copyright with permission to use at non commercial use. At huggingface model, it's MIT. Wich one does apply?

Thanks

**Comment by nupurkmr9** [comment]
Hi, Adobe license applies to the code of custom diffusion. 
Huggingface demo clones this repo, and the wrapper code over it is under MIT. 
I will modify the huggingface license to represent that. Thanks for pointing this out.

**Comment by jaspior** [comment]
Thank you for the clarification!
