### ISSUE TITLE
About given prompts.

### ISSUE THREAD

**Issue by guyuchao** [adobe-research/custom-diffusion#40]
Hi, I want to ask why the moongate.txt and moongate_dog.txt don't contain <new1> placeholder token?

**Comment by nupurkmr9** [comment]
Hi, we didn't use a placeholder token for moongate as it's not a personalized instance of a general category.

**Comment by guyuchao** [comment]
But why in the [table_chair.txt](https://github.com/adobe-research/custom-diffusion/blob/main/prompts/table_chair.txt), it is also not a placeholder token?

**Comment by nupurkmr9** [comment]
In the txt files for multi-concept, I added the placeholder token dynamically (when needed), as any of the two concepts can be \<new1\> (\<new2\>). 
Placeholder token was used for all concepts except moongate. 

Thanks.

**Comment by guyuchao** [comment]
thanks
