### ISSUE TITLE
Trained Models for dog & cat and tortoise plushy & teddybear

### ISSUE THREAD

**Issue by MeixiChenTracy** [adobe-research/custom-diffusion#43]
Hi,

Firstly many thanks for sharing your amazing work!

I'm trying to investigate more on the failure cases i.e. the dog & cat and tortoise plushy & teddybear, but I didn't appear to find them on https://www.cs.cmu.edu/~custom-diffusion/assets/models/ . I wonder if it is possible to get access to those two models as well?

**Comment by nupurkmr9** [comment]
Hi, 
I didn't save the exact checkpoint for these two cases, but I will retrain again with a similar seed and share it soon at the same link, most probably by the end of next week. Hope it will still be helpful. 

Thanks!!

**Comment by MeixiChenTracy** [comment]
> Hi, I didn't save the exact checkpoint for these two cases, but I will retrain again with a similar seed and share it soon at the same link, most probably by the end of next week. Hope it will still be helpful.
> 
> Thanks!!

@nupurkmr9 Thank you so much! That would help a lot!

**Comment by nupurkmr9** [comment]
Hi,
You can now find these models [here](https://www.cs.cmu.edu/~custom-diffusion/assets/failure_case_models/).
Sampling can be done via: 

```
python sample.py --ckpt <pretrained-sd-1.4.ckpt> --prompt "<text-prompt>" --delta_ckpt <path-to-delta-ckpt> --modifier_token "<new1>+<new2>"
```

Thanks.

**Comment by MeixiChenTracy** [comment]
> Hi, You can now find these models [here](https://www.cs.cmu.edu/~custom-diffusion/assets/failure_case_models/). Sampling can be done via:
> 
> ```
> python sample.py --ckpt <pretrained-sd-1.4.ckpt> --prompt "<text-prompt>" --delta_ckpt <path-to-delta-ckpt> --modifier_token "<new1>+<new2>"
> ```
> 
> Thanks.

@nupurkmr9 Found them! Thank you so much!!!
