### ISSUE TITLE
convert.py contains bugs and suggested fixes

### ISSUE THREAD

**Issue by lamwilton** [adobe-research/custom-diffusion#45]
I am trying to run the compvis-to-webui mode and it doesnt work. I went into the code and found some potential bugs. After I tried to fix it, it seems to work although I havent tried using the output models. Please see if they are correct and fix it. Thank you!

Lines 72-73, should be 'and' not 'or'
```
    # convert checkpoint to webui
    if mode in ['diffuser-to-webui' and 'compvis-to-webui']:
```

Lines 91-92, 'compvis_st' is not defined within that scope so I think it should be 'st'
```
            st = torch.load(delta_ckpt)["state_dict"]
            model.load_state_dict(st, strict=False)
```

<img width="887" alt="Screen Shot 2023-02-24 at 3 34 27 PM" src="https://user-images.githubusercontent.com/16893989/221286108-17e9b0cc-9bcd-4846-86a8-86d482b7aa98.png">

**Comment by nupurkmr9** [comment]
Hi, 
Thanks for pointing out the bug. I have corrected for it now.
