### ISSUE TITLE
[ CrossAttention: new-forward pass]

### ISSUE THREAD

**Issue by IemProg** [adobe-research/custom-diffusion#46]
Hi,

Wonderful work, thanks for sharing the code.

I have a question with respect to _new_forward_ pass function defined in **model.py** file. I do not understand why when the cross-attention in True, **you manipulate the key, and value tensors with new variable named modifier**. (line [154-158](https://github.com/adobe-research/custom-diffusion/blob/728c1546d599c8b413dd4524762f56951ab646a3/src/model.py#L155)).

Thanks

**Comment by nupurkmr9** [comment]
Hi, we stop the gradient on the first token of the text transformer output since its always the same and I observed small benefits when doing that.
Hope this clarifies any confusion.

Thanks.
