### ISSUE TITLE
Questions about Custom Diffusion with artistic styles

### ISSUE THREAD

**Issue by BossunWang** [adobe-research/custom-diffusion#48]
Hi, expert
I'm interest on Figure.9. which generated style of artist.
May you share how to train the  V1* art and more detail to combine with V2* wooden pot?

**Comment by nupurkmr9** [comment]
Hi, if you are using the CompVis based training code, you can train for a particular style using the following command. 
```
wget https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt 
bash scripts/finetune_style.sh "art" <path-to-style-images> real_reg/samples_art <name-of-the-exp>  finetune_addtoken.yaml  sd-v1-4.ckpt 
```

This is the command to train a joint model with given style with the "wooden pot".
```
bash scripts/finetune_joint.sh  "art" <path-to-style-images> real_reg/samples_art  "wooden pot" data/wooden_pot real_reg/samples_wooden_pot  <name-of-the-exp> finetune_style_joint.yaml sd-v1-4.ckpt 
```

Hope this is helpful. Let me know if you are interested in the diffusers based script for the same or have any other doubts. 
Thanks!!
