### ISSUE TITLE
How to show cross attention map for checking the issue of failed compositions?

### ISSUE THREAD

**Issue by BossunWang** [adobe-research/custom-diffusion#54]
I would like to check the issue of failed compositions in the figure 16.
And then I find the function "show_cross_attention" from prompt-to-prompt:
[null_text_w_ptp.ipynb](https://github.com/google/prompt-to-prompt/blob/main/null_text_w_ptp.ipynb)
But it's not fit your code to analysis attention map.May you release this code for me to research about this issue?

**Comment by nupurkmr9** [comment]
Hi, 

Prompt-to-prompt can be used with our diffusers-based training and models. 

The original prompt-to-prompt might need to be changed for diffusers==0.14.0. 
I have uploaded a working implementation [here](https://colab.research.google.com/drive/1VTmAbusOzNj85Qzq73BVkNjQMMbHIrVR?usp=sharing). The main changes involve the `ldm_stable` model load and minor modifications in `register_attention_control`. 

Another thing that needs to be changed in prompt-to-prompt is [here](https://github.com/google/prompt-to-prompt/blob/8186230a8ece64c2953271659aa858ec6d02a5cf/ptp_utils.py#L70) to the below line.  
```
noise_pred = model.unet(latents_input, t, context)["sample"]
```
Let me know if you still face any issues. Thanks!

**Comment by yuxu915** [comment]
@nupurkmr9 Hi, thanks for you work, I'd like to ask if you have attention_map visualization codes which are not based on diffusers?  Really thanks for your help!
