### ISSUE TITLE
problem when using diffusers for training

### ISSUE THREAD

**Issue by yuxu915** [adobe-research/custom-diffusion#57]
hi, @nupurkmr9 , thanks for your great work and contribution, but I have some problem while training in diffusers library:
1. I got a `pytorch_lora_weights.bin` rather than p`ytorch_custom_diffusion_weights.bin` after training. Training setting is as default. I'd like to ask if you have any idea, thanks!
2. ` AttributeError: 'Attention' object has no attribute 'cross_attention_norm'`

**Comment by nupurkmr9** [comment]
Hi, following the instruction as [here](https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion) for training along with source install of diffusers saves the `pytorch_custom_diffusion_weights.bin` for me. 

I am not sure why you are facing an error. Can you check if the diffusers has been installed from latest GitHub pull? 
Thanks.

**Comment by yuxu915** [comment]
@nupurkmr9 Thanks for your reply, I update source code and solve the problem.
