### ISSUE TITLE
Anyway to run it with stable diffusion 2.1?

### ISSUE THREAD

**Issue by asrlhhh** [adobe-research/custom-diffusion#60]
I know the work was done with version 1.4, but I am wondering how much work it is to adapt it to 2.1

**Comment by nupurkmr9** [comment]
Hi, 
Thanks for the interest in our work. Custom diffusion [diffusers code](https://github.com/adobe-research/custom-diffusion#training-using-diffusers-library) can be used with 2.1 model version as well. If you are using source install of diffusers repo, it is also supported in it as shown [here](https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion). 

The following arguments need to be changed from the default: 
```
export MODEL_NAME="stabilityai/stable-diffusion-2-1-base"
resolution=768 (in the launch command) 
```

For using 2.1 version with the [CompVis](https://github.com/CompVis/stable-diffusion) codebase will require a wrapper class over the text encoder to enable adding new tokens which is currently not supported. 

Hope this helps. Thanks!

**Comment by asrlhhh** [comment]
Thanks I will try it out!
