### ISSUE TITLE
Is it possible for the fine-tuned model to do inpainting job rather than image generation?

### ISSUE THREAD

**Issue by asrlhhh** [adobe-research/custom-diffusion#61]
Hi, I am wondering if I can use the model fine-tuned for new concept to do inpainting job?

**Comment by hpstyl** [comment]
Very interested in knowing this as well!

**Comment by nupurkmr9** [comment]
Hi, 
I did try our method with Prompt-to-Prompt kind of techniques, e.g., replacing a dog in an image with a pet dog. I haven't tried inpainting extensively, but it should be possible. Can you mention any specific use case that you are thinking of? 
Thanks.

**Comment by asrlhhh** [comment]
Thanks for your response @nupurkmr9 what i wanted to do is more like product placement thing. Sometimes I just want to insert *s into an existing image in a harmonious way
