### ISSUE TITLE
TypeError: ModelCheckpoint.__init__() got an unexpected keyword argument 'every_n_epochs'

### ISSUE THREAD

**Issue by sam-motamed** [adobe-research/custom-diffusion#63]
White trying to  train the cat examples, I am getting the following TypeError. Any ideas what is the cause?

`TypeError: ModelCheckpoint.__init__() got an unexpected keyword argument 'every_n_epochs'`

**Comment by nupurkmr9** [comment]
Hi, 
Can you mention the Pytorch lightning version you are using? 
Thanks.

**Comment by sam-motamed** [comment]
Indeed a lightning version issue. Fixed.
