### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kietbg0079** [adobe-research/custom-diffusion#64]
There are two Licenses in this repo. What's the final License? Do you know if I can use this repo for commercial purposes?

**Comment by nupurkmr9** [comment]
Hi, 
The diffusers library-based implementation is released with an [MIT license](https://github.com/adobe-research/custom-diffusion/blob/main/MIT_License.md). The [CompVis](https://github.com/CompVis/stable-diffusion)-based code is with [Adobe license](https://github.com/adobe-research/custom-diffusion/blob/main/LICENSE.md). 
Each file has its license mentioned at the top. 

We also have custom-diffusion implementation in diffusers [here](https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion).

I hope this answers your question. Thanks.
