### ISSUE TITLE
Moon Gate+ Evaluation q

### ISSUE THREAD

**Issue by isamu-isozaki** [adobe-research/custom-diffusion#66]
Hi! Bit late but amazing work! I was trying to do an evaluation of a method in comparison to your results and I have 2 questions
1. In the prompt directory, for any prompts involving moongate, the placeholder token is absent. Is there a reason for this?
2. For custom diffusion, for generating 1000 images from the 10 categories with 20 prompts each, did you generate 5 images for each prompt+category?
And again thanks a lot for the research!

**Comment by nupurkmr9** [comment]
Hi, thanks for your interest in our work. 
1. We didn't use any placeholder token for moongate as it's not a personalized but a general concept which the model doesn't generate well. 
2. For evaluation we generated 1000 images for each category (50 images per prompt) among the 10 categories, therefore total 10k images. 
3. We also recently released the [customconcept101](https://github.com/adobe-research/custom-diffusion/tree/main/customconcept101) dataset of 101 concepts where we evaluate on 100 images per category using 20 prompts (5 images per prompt), resulting in a total of ~10k images as well. 

Hope this answers your questions.

**Comment by isamu-isozaki** [comment]
@nupurkmr9 Thank you so much! And feel free to close!

**Comment by isamu-isozaki** [comment]
@nupurkmr9 Hi! Sorry one more question. For the image alignment, I did notice some classes have more training images than others. Do you average the image alignment over all the classes or just do a pair wise real-generated image alignment?
