### ISSUE TITLE
How to Visualize Attention Maps to Analyze Compositions?

### ISSUE THREAD

**Issue by aatiibutt** [adobe-research/custom-diffusion#70]
Hi @nupurkmr9, 
Can you please share implementation to visualize attention maps with custom diffusion?

**Comment by nupurkmr9** [comment]
Hi, I used the prompt-to-prompt codebase to visualize attention maps after converting model to diffusers version. I added an implementation in this [issue](https://github.com/adobe-research/custom-diffusion/issues/54) regarding that. 
Let me know if you face any issues with that. Thanks.

**Comment by aatiibutt** [comment]
Thanks @nupurkmr9 for your kind response. Actually, I am using your diffusers-based implementation. After fine-tuning, I get two bin files (i.e., pytorch_custom_diffusion_weights.bin, and <new1>.bin). Can you please guide me how to process these to feed as a model in load_model() function of your provided [implementation](https://colab.research.google.com/drive/1VTmAbusOzNj85Qzq73BVkNjQMMbHIrVR?usp=sharing#scrollTo=Fki9XL0JY8UJ)?
