### ISSUE TITLE
No module named 'diffusers.models.cross_attention'

### ISSUE THREAD

**Issue by htrvu** [adobe-research/custom-diffusion#77]
I have installed the environments as described in README for training with diffusers library:
```
pip install accelerate>=0.24.1
pip install modelcards
pip install transformers>=4.31.0
pip install deepspeed
pip install diffusers==0.21.4
```
And it gives me this error:
```
File "/custom-diffusion/src/diffusers_training.py", line 240, in <module>
    from diffusers.models.cross_attention import CrossAttention
ModuleNotFoundError: No module named 'diffusers.models.cross_attention'
```
Do you update the code for the version 0.21.4 of diffusers?

**Comment by nupurkmr9** [comment]
Hi, thanks for pointing this out. I updated the readme but forgot to update the code :) 
It should hopefully work now.
