### ISSUE TITLE
Missing text prompts?

### ISSUE THREAD

**Issue by Shentao-YANG** [adobe-research/custom-diffusion#91]
Hi

Thank you so much for this great codebase!

It seems like some of the text prompts files referred in `customconcept101/dataset.json` are missing in the `prompts` folder, such as `prompts/plushie.txt` and `prompts/actionfigure.txt`. May I kindly ask if they reside in another folder within this codebase? Else, do you have a plan to upload the full set of text prompts files?

Additionally, how can I get the `customconcept101/regularization/` folder?

Thanks!

**Comment by nupurkmr9** [comment]
Hi, I am not sure which txt files are missing. The `actionfigure.txt` can be found [here](https://github.com/adobe-research/custom-diffusion/blob/main/customconcept101/prompts/actionfigure.txt) and `plushie.txt` is [here](https://github.com/adobe-research/custom-diffusion/blob/main/customconcept101/prompts/plushie.txt). 

The `customconcept101/regularization/`  regularization dataset was scraped from LAION dataset using [clip-retrieval](https://github.com/rom1504/clip-retrieval). But this API seems to be down of late along with the dataset. 
One option is to remove the `--real_prior` flag and the model will generate regularization images. 

I hope this answers your queries. Let me know if you have any other questions. 
Thanks.

**Comment by Shentao-YANG** [comment]
Thank you for your reply! They do resolve my issue!
